### ISSUE TITLE
Allow `Ed25519` with Noise

### ISSUE THREAD

**Issue by cloudhead** [cyphernet-dao/rust-cyphernet#5]
Currently if you set:

```
    const CURVE_NAME: &'static str = "Ed25519";
```
In `cyphernet::EcPk` and try to use that for Noise, you get:
```
thread '' panicked at 'not implemented: curve Ed25519 is not supported by the Noise library', /noise-framework-0.2.0/src/state.rs:275:17
```

We should either remove that associated constant, or not panic, since we now are supporting ECDH on Ed.

**Comment by dr-orlovsky** [comment]
This `CURVE_NAME` is used in construction of Noise protocol name according to http://noiseprotocol.org/noise.html#protocol-names-and-modifiers requirements, thus it can't be removed.

In #9 I added support for the curve.

NB: This is a breaking change which will make old clients incompatible with the new ones (i.e. the encryption will be different and ECDH will not be possible since Noise framework commits to the protocol and curve names as a part of the handshake)

**Comment by cloudhead** [comment]
Good to know, I'll have everyone upgrade their clients.
